In [1]:
import torch

In [2]:
H, W = 200, 200

In [6]:
Z = 8
dtype = torch.float

In [7]:
zs = torch.linspace(0.5, Z - 0.5, 4, dtype=dtype).view(-1, 1, 1).expand(4, H, W) / Z
zs.shape

torch.Size([4, 200, 200])

In [8]:
xs = torch.linspace(0.5, W - 0.5, W, dtype=dtype).view(1, 1, W).expand(4, H, W) / W
xs.shape

torch.Size([4, 200, 200])

In [9]:
ys = torch.linspace(0.5, H - 0.5, H, dtype=dtype).view(1, H, 1).expand(4, H, W) / H
ys.shape

torch.Size([4, 200, 200])

In [10]:
ref_3d = torch.stack((xs, ys, zs), -1)
ref_3d.shape

torch.Size([4, 200, 200, 3])

In [11]:
ref_3d = ref_3d.permute(0, 3, 1, 2).flatten(2).permute(0, 2, 1)
ref_3d.shape

torch.Size([4, 40000, 3])

In [12]:
ref_3d = ref_3d[None].repeat(2, 1, 1, 1).size()
ref_3d

torch.Size([2, 4, 40000, 3])

In [105]:
ref_y, ref_x = torch.meshgrid(
                torch.linspace(
                    0.5, H - 0.5, H, dtype=dtype),
                torch.linspace(
                    0.5, W - 0.5, W, dtype=dtype)
            )
ref_y.shape

torch.Size([250, 300])

In [110]:
bs = 2
ref_y = ref_y.reshape(-1)[None] / H
ref_x = ref_x.reshape(-1)[None] / W
print('ref_y, ref_x:', ref_y.size(), ref_x.size())

ref_y, ref_x: torch.Size([1, 75000]) torch.Size([1, 75000])


In [116]:
ref_2d = torch.stack((ref_x, ref_y), -1)
print(ref_2d.size())
ref_2d = ref_2d.repeat(bs, 1, 1).unsqueeze(2)
ref_2d.size() ##### shape (bs, num_keys, num_levels, 2).


torch.Size([1, 75000, 2])


torch.Size([2, 75000, 1, 2])

In [108]:
ref_2d.shape

torch.Size([2, 75000, 1, 2])

In [30]:
tensor1 = torch.randn(4,2,6,40001, 9,1)
tensor2 = torch.randn(4,2,6,40001, 5,9)

In [31]:
tensor3 = torch.matmul(tensor2, tensor1)

In [32]:
tensor3.size()

torch.Size([4, 2, 6, 40001, 5, 1])

In [5]:
a = torch.ones([8, 4, 5, 6])
print('a =',a.size())
b = torch.ones([8, 4, 5, 6])
print('b =',b.size())
c = a+b
print('c =',c.size())

a = torch.Size([8, 4, 5, 6])
b = torch.Size([8, 4, 5, 6])
c = torch.Size([8, 4, 5, 6])


In [7]:
c

tensor([[[[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]]],


        [[[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.],
          [2., 2

In [1]:
###测试attenion_weights


In [1]:
import torch
num_head = 8
dim = 256
num_value = 30825
a = torch.randn(6, num_value, num_head, dim//num_head)
b = torch.randn(6, num_value, num_head, dim//num_head)
c = torch.randn(6, num_value, num_head, dim//num_head)
d = torch.randn(6, num_value, num_head, dim//num_head)



In [4]:
eee = torch.stack([a,b,c,d], dim = -2)
eee.size()

torch.Size([6, 30825, 8, 4, 32])

In [40]:
eee.sum(-1).size()

torch.Size([6, 30825, 8, 4])

torch.Size([6, 30825, 8, 128])

torch.Size([6, 30825, 8, 128])

In [13]:
attention = torch.randn([48, 1, 9675, 32])

In [14]:
sampling_value_list = torch.randn([48, 32, 9675, 32])

In [15]:
output = sampling_value_list * attention

In [52]:
output.sum(-1).size()

torch.Size([48, 32, 9675])

In [26]:
a = torch.tensor([[1, 2], [2, 3]])
a.size()

torch.Size([2, 2])

In [25]:
b = torch.tensor([[[1,2],[2,3]],[[-1,-2],[-2,-3]]])
b

tensor([[[ 1,  2],
         [ 2,  3]],

        [[-1, -2],
         [-2, -3]]])

In [21]:
c = a * b
c

tensor([[[ 1,  4],
         [ 4,  9]],

        [[-1, -4],
         [-4, -9]]])

In [30]:
a = torch.tensor([[[1, 2], [2, 3]], [[-1, -2], [-2, -3]]])
b = torch.tensor([[[1,2],[2,3]],[[-1,-2],[-2,-3]]])
a.size(), b.size()

(torch.Size([2, 2, 2]), torch.Size([2, 2, 2]))

In [28]:
d = a * b
d

tensor([[[ 1,  4],
         [ 4,  9]],

        [[-1, -4],
         [-4, -9]]])